// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzckmtfyzjpbhryrogce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6Y2ttdGZ5empwYmhyeXJvZ2NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDA0MTgsImV4cCI6MjA2ODE3NjQxOH0.zTmtj7IfQSlUp7S7wg4q_mgrymHDDf77oAykddof71c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});